version: 0.2

env:
  variables:
    AWS_REGION: "eu-north-1"
    ECR_REPO: "sqs-consumer"
    IMAGE_TAG: "latest"
    # OPTIONAL ECS deploy vars:
    # ECS_CLUSTER: "cdc-cluster"
    # ECS_SERVICE: "sqs-consumer-svc"
    # TD_FAMILY: "sqs-consumer"

phases:
  pre_build:
    commands:
      - echo "==> Resolve account & ECR URI"
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}
      - echo "==> Ensure ECR repo exists"
      - aws ecr describe-repositories --repository-names ${ECR_REPO} --region ${AWS_REGION} >/dev/null 2>&1 || aws ecr create-repository --repository-name ${ECR_REPO} --region ${AWS_REGION} >/dev/null
      - echo "==> Login to ECR"
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
  build:
    commands:
      - echo "Build image directly with final tag (no 'docker tag' step)"
      - docker build -t ${ECR_URI}:${IMAGE_TAG} .
      - echo "Push"
      - docker push ${ECR_URI}:${IMAGE_TAG}
artifacts:
  files: []
